Single visit page form list
MikenasIgnas/DLC-Journal-FrontEnd pull request #2
Opened 2023-12-05 12:41 UTC by MikenasIgnas

2023-12-05 14:21 UTC, NorbertasM requested changes
Visiškai jokios kodo struktūros. Vienose vietosie sulyguota, kitose belekaip. Sunku vertint kodo logiką kai sunku perskaityt patį kodą.

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/ClientCompanyListComponents/ClientsEmployeesTab/ClientsEmployeesTab.tsx
> +        <Button onClick={() => setModalState({...modalState, isEmployeeAdditionModalOpen: true})}>Pridėti darbuotoją</Button>
Paduodi modalState ir setModalState iš parento, tai toj funkcijoj gali naudot parento modalState. Nėr čia ko kaip ping pongą su parametrais žaist.
Kitas klausimas. Gal metodas turėtų vadintis openEmployeeAdditionModal ir jokių parametrų į jį nepaduot, jei visą laiką tik true darai. Visą logiką atlikt funkcijoj

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/ClientCompanyListComponents/CollocationFormList.tsx
> +                  <Row gutter={[16, 16]} style={{display: 'flex'}} >
kodėl ne klasė? Row komponentas ne defaultu flex?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/ClientCompanyListComponents/CollocationSelectors.tsx
> +      <Collapse style={{marginBottom: '10px', marginTop: '10px', width: '360px'}}>
kodėl ne klasė?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/ClientCompanyListComponents/CollocationSelectors.tsx
>          <Panel style={{padding: '10px'}} header={collocationSite} key={colocationId}>
kodėl ne klasė?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/ClientCompanyListComponents/CollocationSelectors.tsx
> +                          <Checkbox.Group options={premise.racks} style={{
kodėl ne klasė?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/VisitiRegistrationComponents/SelectedCollocationList.tsx
> +            <Card style={{ margin: '10px', width: '100%' }} key={i} title={objEntries[0][0]}>
kodėl ne klasė?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/VisitiRegistrationComponents/VisitDateItem.tsx
> +    <div style={{display: 'flex', alignItems: 'center', justifyContent: 'center'}}>
kodėl ne klasė?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/VisitiRegistrationComponents/VisitDateItem.tsx
> +        <div style={{display: 'flex'}}>
kodėl ne klasė?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/VisitiRegistrationComponents/VisitDateItem.tsx
> +          <div style={{display: 'flex', justifyContent: 'center', alignItems: 'center'}}>
kodėl ne klasė?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/VisitiRegistrationComponents/VisitRegistrationForm.tsx
> +  form:             FormInstance<any>
any?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/VisitiRegistrationComponents/VisitRegistrationForm.tsx
> +      <Button style={{margin: '10px'}} icon={<PlusCircleOutlined />} onClick={() => setOpen(true)}>Pridėti Lankytoją</Button>
kodėl ne klasė?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/VisitiRegistrationComponents/VisitorsListItem.tsx
> +  form:   FormInstance<any>
any?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/VisitiRegistrationComponents/VisitorsListItem.tsx
> +  console.log(form.getFieldValue('visitors')[item.name].selectedVisitor.permissions)
???

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/VisitiRegistrationComponents/VisitorsListItem.tsx
>          style={{flex: '0 0'}}
kodėl ne klasė?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/VisitiRegistrationComponents/VisitorsListItem.tsx
> +              <div style={{ width: '100px', display: 'flex', alignItems: 'center', justifyContent: 'space-around' }}>
kodėl ne klasė?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/VisitiRegistrationComponents/VisitorsListItem.tsx
> +                <CheckOutlined style={{ color: '#4de44d', fontSize: '17px' }} />
kodėl ne klasė?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/VisitiRegistrationComponents/VisitorsListItem.tsx
> +        <div>{form.getFieldValue('visitors')[item.name].selectedVisitor.permissions.map((el:any) => <div>{el}</div>)}</div>
neįmano skaityt. Any?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/VisitiRegistrationComponents/VisitorsListItem.tsx
> +  form:   FormInstance<any>
Ar reikia visos formos instance?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/VisitiRegistrationComponents/VisitorsSelectCard.tsx
> +          : [...(prevSelectedVisitors || []), item]
a nesidubluoji?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/DLCJournalComponents/VisitiRegistrationComponents/VisitorsSelectCard.tsx
> +    <Card style={{ width: 300, marginTop: 16, border: isSelected ? '2px solid blue' : '1px solid #e8e8e8'}} onClick={() => handleCardClick()}>
kodėl ne klasė?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/UniversalComponents/PageLayout/PageLayout.tsx
> +            <div style={{display: 'flex', flexDirection: 'column' ,justifyContent: 'space-between', height: '95%'}} >
kodėl ne klasė?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/UniversalComponents/PageLayout/PageLayout.tsx
> +                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-around'}}>
kodėl ne klasė?

2023-12-05 14:21 UTC, NorbertasM commented on src/components/UniversalComponents/PageLayout/PageLayout.tsx
> +                  {!collapsed && <div style={{fontSize: '15px'}}>{userName}</div>}<LogoutOutlined style={{fontSize: '20px'}} onClick={userLogOut}/>
kodėl ne klasė?

2023-12-05 14:21 UTC, NorbertasM commented on src/pages/DLC-JounalPages/VisitRegistrationPage.tsx
> +      console.log(values)
?

2023-12-05 14:21 UTC, NorbertasM commented on src/pages/DLC-JounalPages/VisitRegistrationPage.tsx
> +  const registerVisit = async(values: VisitsType) => {
Ar čia registruoji ar tik updatini vizitą?

2023-12-05 14:21 UTC, NorbertasM commented on src/pages/DLC-JounalPages/VisitRegistrationPage.tsx
> +      console.log(values)
?

2023-12-05 14:21 UTC, NorbertasM commented on src/pages/DLC-JounalPages/VisitsPage.tsx
> +      <th style={{ width: 130, padding: '12px 6px' }}>Vizito Tikslas</th>
kodėl ne klasė?

2023-12-05 14:21 UTC, NorbertasM commented on src/pages/DLC-JounalPages/VisitsPage.tsx
> +      <th style={{ width: 100, padding: '12px 6px' }}>Klientas</th>
kodėl ne klasė?

2023-12-05 14:21 UTC, NorbertasM commented on src/pages/DLC-JounalPages/SingleVisitPage.tsx
>          )}
Skaidyk į atskirus komponentus, custom hookus ir funkcijas.

2023-12-05 18:09 UTC, MikenasIgnas commented on src/components/DLCJournalComponents/ClientCompanyListComponents/ClientsEmployeeList.tsx
> +    <div style={{width: '100%'}}>
i hate classes

2023-12-05 18:13 UTC, MikenasIgnas commented on src/components/DLCJournalComponents/ClientCompanyListComponents/ClientsEmployeesTab/ClientsEmployeesTab.tsx
> +    <div style={{width: '100%',display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center'}}>
i hate classes

2023-12-05 18:13 UTC, MikenasIgnas commented on src/components/DLCJournalComponents/ClientCompanyListComponents/ClientsEmployeesTab/ClientsEmployeesTab.tsx
> +      <div style={{width: '50%', display: 'flex',justifyContent: 'center'}}>
I hate classes

2023-12-05 18:19 UTC, MikenasIgnas commented on src/pages/DLC-JounalPages/VisitsPage.tsx
> +      <th style={{ width: 100, padding: '12px 6px' }}>Klientas</th>
I hate classes

2023-12-05 20:13 UTC, MikenasIgnas commented on src/pages/DLC-JounalPages/VisitRegistrationPage.tsx
> +  const registerVisit = async(values: VisitsType) => {
Registruoju

2023-12-05 23:03 UTC, MikenasIgnas commented on src/components/DLCJournalComponents/ClientCompanyListComponents/SubClientsTab/SubClientsTab.tsx
> +  }
Idejau i useEffecta

2023-12-06 00:17 UTC, MikenasIgnas commented on src/components/DLCJournalComponents/VisitiRegistrationComponents/VisitorsListItem.tsx
> +            {form.getFieldValue('visitors')[item.name].signature ? (
Nežinau kaip paduot, bandžiau form.getFieldValue([item.name, 'signature']) ir dar keliai budais bet nepavyko. skill issue

2023-12-06 00:18 UTC, MikenasIgnas commented on src/components/DLCJournalComponents/VisitiRegistrationComponents/VisitorsListItem.tsx
> +  form:   FormInstance<any>
tipa kopijavau nuo const [form]  = Form.useForm(), nereikia viso perduot?

2023-12-06 02:54 UTC, MikenasIgnas commented on src/components/DLCJournalComponents/ClientCompanyListComponents/ClientsEmployeesTab/ClientsEmployeesTab.tsx
> +        <Button onClick={() => setModalState({...modalState, isEmployeeAdditionModalOpen: true})}>Pridėti darbuotoją</Button>
Tai modal state yra toks:   
const [modalState, setModalState] = React.useState<ModalStateType>({
    editClientsEmployee:                false,
    edit:                                           false,
    openEmployeeAdditionModal: false,
    isCompanyAdded:                     false,
    isModalOpen:                            false,
  })
tai ...modal state paduodu, kad visas kitas reiksmes paliktu pakeistu tik openEmployeeAdditionModal, at kazka netaip suprantu?

2023-12-12 15:38 UTC, NorbertasM commented on src/components/DLCJournalComponents/ClientCompanyListComponents/ClientsEmployeesTab/ClientsEmployeesTab.tsx
> +        <Button onClick={() => setModalState({...modalState, isEmployeeAdditionModalOpen: true})}>Pridėti darbuotoją</Button>
padarai funkcija, kuri pakeičia tą vieną property ir tiesiog tą funkciją paduodi, vietoj setModalState funkcijos ir visų jo properčių

2024-01-01 12:14 UTC, merged